image: docker:stable
#image: 192.168.31.140:5000/centos

variables:
  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: tcp://localhost:2375

services:
- docker:dind

before_script:
- ls /var/run/
- ls /usr/bin/kubectl
- kubectl help
- kubectl get pods  
- docker info
- uname -a;ps auxwww

build:
 stage: build  
 tags:
 - shell,kuber
 script:    
 - cd /yunwei/django
 - version=`date +%Y%m%d-%H%M%S`
 - docker build -t 192.168.31.140:5000/python:v$version -f ./dockerfile.django .  
 - docker push 192.168.31.140:5000/python:v$version
 - kubectl set image deployment/student student=192.168.31.140:5000/python:v$version -n default
#date +%Y%m%d-%H%M%S
# - sh ./docker-run.sh

